name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: 🚀 Features
    labels:
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🔧 Chores
    labels:
      - chore
  - title: 🧪 Tests
    labels:
      - test
  - title: 📝 Documentation
    labels:
      - docs
  - title: ⚙️ Refactoring
    labels:
      - refactor
  - title: ♻️ Code Style
    labels:
      - style
  - title: 📦 Build
    labels:
      - build
  - title: 🚦 CI
    labels:
      - ci

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'

exclude-labels:
  - skip-changelog

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: [Compare changes](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG)
